'use client'

import Link from 'next/link'
import { ArrowLeft, Award, Flame, Rocket, Sparkles, Star, Trophy, Users, Zap } from 'lucide-react'

type Winner = { rank: number; prize: string; teamName: string; members: string[]; emoji: string }

const winners: Winner[] = [
  { rank: 1, prize: '₹10,000', teamName: 'Yurt', members: ['Sanjay T', 'Santhosh A', 'Miralani R'], emoji: '🥇' },
  { rank: 2, prize: '₹5,000', teamName: 'The Giants', members: ['Vaishnavi M', 'Likitha G'], emoji: '🥈' },
  { rank: 3, prize: '₹3,000', teamName: 'The Fighters', members: ['Samyuktha K', 'Nithin', 'Tarun K'], emoji: '🥉' },
  { rank: 4, prize: '₹1,500', teamName: 'Vector Dubs', members: ['Vijay Tharun', 'Vikas', 'Nishaliya K'], emoji: '🏅' },
  { rank: 5, prize: '₹1,000', teamName: 'Infiners', members: ['Gokul M', 'Sharan K'], emoji: '🏅' },
  { rank: 6, prize: 'Certificate of Recognition', teamName: 'Ctrl Freaks', members: ['Ridhesha', 'Ranjith'], emoji: '🏅' },
  { rank: 7, prize: 'Certificate of Recognition', teamName: 'Trinity', members: ['Prashana S', 'Priyadharshini S', 'Hanshikaa S'], emoji: '🏅' },
  { rank: 8, prize: 'Certificate of Recognition', teamName: 'Tech Vibe', members: ['Bhavana Sri G', 'Ashwitha R'], emoji: '🏅' },
  { rank: 9, prize: 'Certificate of Recognition', teamName: 'Algnite', members: ['Nadhin P', 'Rhea R', 'Pranavdhanh C'], emoji: '🏅' },
  { rank: 10, prize: 'Certificate of Recognition', teamName: 'Brain Spark', members: ['Shavishna A', 'Srinickitha S', 'Shivasakthi M'], emoji: '🏅' },
]

const particles = Array.from({ length: 16 }, (_, i) => ({ left: `${(i * 29 + 9) % 100}%`, top: `${(i * 47 + 13) % 100}%`, size: `${(i % 4) + 2}px`, duration: `${(i % 5) + 5}s`, delay: `${i % 4}s` }))

export default function HackathonWinnersPage() {
  const [champion, second, third, ...rest] = winners
  return <main className="relative min-h-screen overflow-x-clip bg-[#060607] text-white">
    <style>{`@keyframes drift{0%,100%{transform:translate3d(0,0,0);opacity:.2}50%{transform:translate3d(10px,-24px,0);opacity:.8}}@keyframes gold-shimmer{0%,100%{background-position:180% center}50%{background-position:-80% center}}.gold-text{background:linear-gradient(90deg,#f59e0b,#fef3c7,#fbbf24,#d97706);background-size:200% auto;-webkit-background-clip:text;background-clip:text;color:transparent;animation:gold-shimmer 6s ease-in-out infinite}@media (prefers-reduced-motion:reduce){.gold-text,.hackathon-particle{animation:none!important}}`}</style>
    <div aria-hidden className="pointer-events-none fixed inset-0 overflow-hidden"><div className="absolute left-1/2 top-[-18rem] h-[36rem] w-[36rem] -translate-x-1/2 rounded-full bg-amber-500/[0.12] blur-[120px]" /><div className="absolute -left-48 top-[34rem] h-[28rem] w-[28rem] rounded-full bg-purple-700/[0.13] blur-[120px]" /><div className="absolute -right-48 top-[52rem] h-[28rem] w-[28rem] rounded-full bg-red-700/[0.1] blur-[120px]" />{particles.map((p, i) => <span key={i} className="hackathon-particle absolute rounded-full bg-amber-300/40" style={{ left: p.left, top: p.top, width: p.size, height: p.size, animation: `drift ${p.duration} ease-in-out ${p.delay} infinite` }} />)}</div>
    <div aria-hidden className="pointer-events-none absolute inset-x-0 top-[30rem] h-[42rem] opacity-40 [background-image:linear-gradient(90deg,transparent_0%,rgba(251,191,36,.12)_49.8%,rgba(251,191,36,.12)_50.2%,transparent_100%),repeating-linear-gradient(0deg,transparent_0,transparent_5.5rem,rgba(255,255,255,.045)_5.55rem,rgba(255,255,255,.045)_5.6rem)] [mask-image:linear-gradient(to_bottom,transparent,black_18%,black_80%,transparent)]" />
    <div className="relative mx-auto w-full max-w-7xl px-4 pb-14 pt-4 sm:px-6 sm:pb-20 sm:pt-7 lg:px-8">
      <header className="flex flex-col items-stretch justify-between gap-3 min-[440px]:flex-row min-[440px]:items-center"><Link href="/" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.055] px-4 py-2.5 text-sm font-semibold text-white/85 transition hover:border-white/25 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-amber-300/80"><ArrowLeft className="h-4 w-4" />Back to Home</Link><div className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-amber-400/20 bg-amber-500/[0.09] px-4 py-2.5 text-xs font-bold uppercase tracking-[0.14em] text-amber-200"><Sparkles className="h-4 w-4" />2026 Hackathon</div></header>
      <section className="mx-auto mt-12 max-w-4xl text-center sm:mt-16"><div className="inline-flex max-w-full items-center justify-center gap-2 rounded-full border border-amber-400/30 bg-amber-500/[0.1] px-4 py-2 text-[10px] font-bold uppercase tracking-[0.15em] text-amber-200 sm:px-5 sm:text-xs sm:tracking-[0.28em]"><Trophy className="h-4 w-4 shrink-0" />Winners Announcement</div><h1 className="gold-text mt-5 text-4xl font-black leading-[0.96] tracking-tight sm:mt-7 sm:text-6xl lg:text-8xl">Hackathon 2026</h1><p className="mt-3 text-base font-bold text-white sm:text-xl lg:text-2xl">🏆 The Champions of Innovation</p><dl className="mx-auto mt-7 grid max-w-2xl grid-cols-3 divide-x divide-white/10 rounded-2xl border border-white/[0.09] bg-white/[0.035] px-1 py-4 sm:mt-9 sm:px-4 sm:py-5"><Metric icon={<Users />} value="27" label="Participants" /><Metric icon={<Award />} value="10" label="Winning Teams" /><Metric icon={<Flame />} value="2026" label="Season" /></dl><div className="mt-6 flex flex-wrap justify-center gap-2 sm:gap-3"><Pill icon={<Zap />} tone="amber" label="Build" /><Pill icon={<Rocket />} tone="violet" label="Compete" /><Pill icon={<Star />} tone="blue" label="Win" /></div></section>
      <section className="mt-16 sm:mt-24" aria-labelledby="top-three"><SectionHeading id="top-three" eyebrow="Final standings" title={<>Top 3 <span className="gold-text">Champions</span></>} description="The brightest minds who conquered the challenge." /><div className="mx-auto mt-7 flex max-w-5xl items-center gap-3 text-[10px] font-bold uppercase tracking-[0.22em] text-amber-200/55 sm:mt-9"><span className="h-px flex-1 bg-gradient-to-r from-transparent to-amber-300/50" />Brandnest Awards<span className="h-px flex-1 bg-gradient-to-l from-transparent to-amber-300/50" /></div><div className="mx-auto mt-5 grid max-w-5xl grid-cols-1 gap-5 sm:mt-7 sm:grid-cols-3 sm:items-end sm:gap-4 lg:gap-6"><div className="order-2 sm:order-1"><PodiumCard winner={second} /></div><div className="order-1 sm:order-2"><ChampionCard winner={champion} /></div><div className="order-3"><PodiumCard winner={third} /></div></div></section>
      <section className="mt-16 sm:mt-24" aria-labelledby="all-winners"><SectionHeading id="all-winners" eyebrow="Every idea mattered" title={<>All <span className="gold-text">Winners</span></>} description="Congratulations to every team that made it." /><div className="mt-8 grid grid-cols-1 gap-4 sm:mt-10 sm:grid-cols-2 sm:gap-5 lg:grid-cols-3">{rest.map(winner => <RankCard key={winner.rank} winner={winner} />)}</div></section>
      <section className="mt-16 border-y border-white/[0.09] bg-gradient-to-r from-red-950/25 via-white/[0.035] to-purple-950/25 px-5 py-12 text-center sm:mt-24 sm:px-10 sm:py-16"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-amber-400/20 bg-amber-400/10"><Trophy className="h-7 w-7 text-amber-300" /></div><h2 className="mt-5 text-3xl font-black tracking-tight sm:text-4xl">Congratulations 🎉</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-white/65 sm:text-base">Every team showed incredible creativity and hard work. This is just the beginning — keep building, keep innovating, and keep winning!</p></section>
    </div></main>
}

function Metric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="flex min-w-0 flex-col items-center gap-1 px-2 text-center"><span className="text-amber-300 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><dd className="text-base font-black leading-none text-white sm:text-2xl">{value}</dd><dt className="text-[10px] font-medium leading-tight text-white/55 sm:text-xs">{label}</dt></div> }
function Pill({ icon, tone, label }: { icon: React.ReactNode; tone: 'amber' | 'violet' | 'blue'; label: string }) { const styles = { amber: 'border-amber-400/20 bg-amber-500/[0.08] text-amber-100', violet: 'border-purple-400/20 bg-purple-500/[0.08] text-purple-100', blue: 'border-sky-400/20 bg-sky-500/[0.08] text-sky-100' }; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-semibold ${styles[tone]}`}><span className="[&>svg]:h-3.5 [&>svg]:w-3.5">{icon}</span>{label}</span> }
function SectionHeading({ id, eyebrow, title, description }: { id: string; eyebrow: string; title: React.ReactNode; description: string }) { return <div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[0.24em] text-amber-300/80 sm:text-xs">{eyebrow}</p><h2 id={id} className="mt-2 text-2xl font-black tracking-tight sm:text-4xl">{title}</h2><p className="mt-2 text-sm text-white/55 sm:text-base">{description}</p></div> }
function ChampionCard({ winner }: { winner: Winner }) { return <article className="relative overflow-hidden rounded-3xl border border-amber-300/40 bg-[linear-gradient(145deg,rgba(120,72,5,.58),rgba(29,20,5,.78)_45%,rgba(5,5,6,.94))] p-5 shadow-[0_0_55px_rgba(245,158,11,.18)] sm:p-6 lg:p-8"><div aria-hidden className="absolute -right-12 -top-16 h-48 w-48 rounded-full bg-amber-300/20 blur-3xl" /><div className="relative text-center"><span className="text-4xl drop-shadow-[0_0_14px_rgba(251,191,36,.65)] sm:text-5xl">👑</span><div className="mx-auto mt-3 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-100 via-amber-400 to-amber-600 text-3xl shadow-lg shadow-amber-500/30">{winner.emoji}</div><p className="mt-4 text-xs font-bold uppercase tracking-[0.2em] text-amber-100/80">First place</p><h3 className="mt-1 break-words text-3xl font-black tracking-tight sm:text-4xl">{winner.teamName}</h3><p className="mt-2 text-xl font-black text-amber-200 sm:text-2xl">{winner.prize}</p><MemberChips members={winner.members} tone="gold" /></div></article> }
function PodiumCard({ winner }: { winner: Winner }) { const second = winner.rank === 2; const style = second ? 'border-slate-300/30 bg-gradient-to-b from-slate-300/[0.12] to-white/[0.035] text-slate-100' : 'border-orange-300/30 bg-gradient-to-b from-orange-500/[0.13] to-white/[0.035] text-orange-100'; return <article className={`h-full rounded-3xl border p-5 sm:p-6 ${style}`}><div className="text-center"><span className="text-3xl">{winner.emoji}</span><p className="mt-3 text-xs font-bold uppercase tracking-[0.17em] opacity-80">{second ? 'Second place' : 'Third place'}</p><h3 className="mt-1 break-words text-xl font-black text-white sm:text-2xl">{winner.teamName}</h3><p className="mt-1 text-base font-bold">{winner.prize}</p><MemberChips members={winner.members} tone={second ? 'silver' : 'bronze'} /></div></article> }
function RankCard({ winner }: { winner: Winner }) { return <article className="group min-w-0 rounded-2xl border border-white/[0.09] bg-white/[0.04] p-4 transition duration-200 hover:border-amber-300/30 hover:bg-white/[0.065] sm:p-5"><div className="flex min-w-0 items-start gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-white/10 bg-black/20 text-sm font-black text-amber-200">#{winner.rank}</span><div className="min-w-0 flex-1"><div className="flex min-w-0 items-start justify-between gap-2"><h3 className="break-words text-base font-black leading-tight text-white sm:text-lg">{winner.teamName}</h3><span className="shrink-0 text-xl" aria-hidden>{winner.emoji}</span></div><p className="mt-1 break-words text-xs font-bold leading-snug text-amber-200/90 sm:text-sm">{winner.prize}</p></div></div><MemberChips members={winner.members} tone="neutral" /></article> }
function MemberChips({ members, tone }: { members: string[]; tone: 'gold' | 'silver' | 'bronze' | 'neutral' }) { const styles = { gold: 'border-amber-200/25 bg-amber-300/10 text-amber-50', silver: 'border-slate-200/20 bg-slate-300/10 text-slate-100', bronze: 'border-orange-200/20 bg-orange-300/10 text-orange-50', neutral: 'border-white/10 bg-black/20 text-white/70' }; return <div className="mt-4 flex flex-wrap justify-center gap-1.5">{members.map(member => <span key={member} className={`max-w-full break-words rounded-full border px-2.5 py-1 text-xs font-medium leading-tight ${styles[tone]}`}>{member}</span>)}</div> }
